openapi: "3.0.2"

info:
  title: Template API Documentation
  description: Manage API endpoints.
  version: 0.0.1

servers:
  - url: http://localhost:8000/api/v1

paths:
  # Write your own API endpoints
  /auth/login:
    # endpoint GET /buku
    post:
      tags:
        - Authentication
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "admin@example.com"
                password:
                  type: string
                  example: "admin"
                is_remember_me:
                  type: boolean
                  example: true
      responses:
        200:
          content:
  /auth/reset-password:
    # endpoint GET /buku
    post:
      tags:
        - Authentication
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                old_password:
                  type: string
                  example: "123456"
                new_password:
                  type: string
                  example: "123456"
                confirm_password:
                  type: string
                  example: "123456"
      responses:
        200:
          content:
  /auth/refresh-token:
    # endpoint GET /buku
    post:
      tags:
        - Authentication
      responses:
        200:
          content:
  /buku:
    # endpoint GET /buku
    get:
      tags:
        - Buku
      responses:

